onboarding = false

[theme]
name = "catppuccin"

[keys]
prefix = "ctrl+a"

detach = "prefix+d"
previous_workspace = "prefix+k"
next_workspace = "prefix+j"

[experimental]
pane_history = true

[ui.toast]
delivery = "terminal"

[ui.sound]
enabled = true
